name: MaehAntiBot
description: Smart AntiBot Detection for Minecraft Server.
version: 1.3
api-version: 1.13
author: DedInc.
main: com.github.dedinc.maehantibot.MaehAntiBot
commands:
  mab:
    description: Reload command.
    usage: /<command>
    permission: maehantibot.reload